spring:
  datasource:
    url: jdbc:mysql://152.136.191.57:3306/demo1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: wang
    password: 123wang321
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl